package transform

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/compose-spec/compose-go/v2/types"

	"github.com/Muronuch/grove/internal/meta"
)

func Marshal(p *types.Project) ([]byte, error) {
	b, err := p.MarshalYAML()
	if err != nil {
		return nil, fmt.Errorf("serialise compose model: %w", err)
	}
	header := fmt.Sprintf("# Generated by %s %s. Do not edit: it is rewritten on every `%s up`.\n"+
		"# Source of truth is the project's own compose file plus %s.toml.\n",
		meta.Name, meta.VersionString(), meta.Name, meta.Name)
	return append([]byte(header), b...), nil
}

func Write(p *types.Project, path string) error {
	b, err := Marshal(p)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, b, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
