package transform

import (
	"context"
	"flag"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Muronuch/grove/internal/config"
)

var update = flag.Bool("update", false, "rewrite the expected.yaml golden files")

const workdirPlaceholder = "/WORKDIR"

func TestTransform(t *testing.T) {
	cases, err := os.ReadDir(filepath.Join("testdata", "transform"))
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range cases {
		if !c.IsDir() {
			continue
		}
		t.Run(c.Name(), func(t *testing.T) {
			runTransformCase(t, c.Name())
		})
	}
}

func runTransformCase(t *testing.T, name string) {
	t.Helper()
	src := filepath.Join("testdata", "transform", name)
	dir := t.TempDir()
	copyDir(t, src, dir)

	cfg, err := config.Load(filepath.Join(dir, config.FileName))
	if err != nil {
		t.Fatalf("config: %v", err)
	}

	ec := Context{
		Project:  cfg.Project.Name,
		Slug:     "feat-x",
		Slot:     3,
		Repo:     "demo",
		Worktree: dir,
		Headless: strings.Contains(name, "headless"),
	}

	model, err := LoadForProject(context.Background(), cfg, dir, ec.ComposeProject(), nil)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	res, err := Apply(model, cfg, ec)
	if err != nil {
		t.Fatalf("apply: %v", err)
	}

	got, err := Marshal(res.Project)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	normalised := normalise(string(got), dir)
	if codes := res.Findings.Codes(); len(codes) > 0 {
		normalised += "\n# findings: " + strings.Join(codes, ", ") + "\n"
	}

	golden := filepath.Join(src, "expected.yaml")
	if *update {
		if err := os.WriteFile(golden, []byte(normalised), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("%v (run: go test ./internal/transform -update)", err)
	}
	if normalised != string(want) {
		t.Errorf("transformed model differs from %s\n--- got ---\n%s\n--- want ---\n%s",
			golden, normalised, string(want))
	}
}

func normalise(s, dir string) string {
	for _, form := range []string{dir, filepath.ToSlash(dir), strings.ReplaceAll(dir, `\`, `\\`)} {
		s = strings.ReplaceAll(s, form, workdirPlaceholder)
	}
	var out []string
	for _, line := range strings.Split(s, "\n") {
		if strings.HasPrefix(line, "# Generated by") {
			line = "# Generated by grove."
		}
		out = append(out, strings.ReplaceAll(line, `\`, "/"))
	}
	return strings.Join(out, "\n")
}

func copyDir(t *testing.T, src, dst string) {
	t.Helper()
	err := filepath.WalkDir(src, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, p)
		if err != nil {
			return err
		}
		if rel == "expected.yaml" {
			return nil
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		b, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		return os.WriteFile(target, b, 0o644)
	})
	if err != nil {
		t.Fatal(err)
	}
}
